#include "src/game/envfx_snow.h"

const GeoLayout ab_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_aship0_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_aship1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_aship3_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_ashipbo_mesh_layer_1),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -132, -163, -372, 90, 0, -28),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ab_dl_Azure_Abyss2_002_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ab_dl_Azure_Abyss2_003_mesh_layer_4),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 0, ab_dl_Azure_Abyss2_004_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_TRANSPARENT, 90, 0, 0, ab_dl_Azure_Abyss2_005_mesh_layer_5),
		GEO_ROTATION_NODE(LAYER_OPAQUE, 90, 0, 0),
		GEO_ROTATION_NODE(LAYER_OPAQUE, 90, 0, 0),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -205, 0, 90, 0, 0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_Azure_Abyss2_009_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ab_dl_casinopolis1_005_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_casinopolis1_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_casinopolis1_006_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ab_dl_cc_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_cc_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ab_dl_cc_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ab_dl_Plane_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_Plane_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ab_dl_Plane_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_Plane_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_Plane_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_Plane_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_Plane_006_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, ab_dl_Plane_007_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_Plane_008_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ab_dl_tf_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ab_dl_zw_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ab_dl_zw_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ab_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ab_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
